export const FE_ROUTES = {
  SIGNIN: '/signin',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  SETTINGS_SYSTEM: '/settings/system',
  SETTINGS_SECURITY: '/settings/security',
  SETTINGS_NOTIFICATION: '/settings/notification',
  SETTINGS_INTEGRATION: '/settings/integration',
  SETTINGS_USER_PREFERENCE: '/settings/user-preference',
  CONNECTION: '/connection',
  REPORT_TYPE: '/report-type',
  REPORT: '/report',
  REPORT_DETAILS: '/report/report-details',
  SCHEDULED_REPORT: '/scheduled-report',
  HOME: '/',
} as const;
