export const TOAST_TITLES = {
  SUCCESS: 'Success',
  ERROR: 'Error',
  WARNING: 'Warning',
  DELETED: 'Deleted',
  UPDATED: 'Updated',
  LOGIN_FAILED: 'Login failed',
  LOGIN_SUCCESSFUL: 'Login successful',
  SESSION_EXPIRED: 'Session expired',
  DOWNLOAD_FAILED: 'Download failed',
  FAILED_TO_DELETE_CONNECTION: 'Failed to delete connection',
  FAILED_TO_SCHEDULE_REPORT: 'Failed to schedule report',
  FAILED_TO_DELETE_REPORT_TYPE: 'Failed to delete report type',
  ERROR_CREATING_USER: 'Error creating user',
  ERROR_UPDATING_USER: 'Error updating user',
  ERROR_DELETING_USER: 'Error deleting user',
  ERROR_CREATING_USER_ROLE: 'Error creating user role',
  ERROR_UPDATING_USER_ROLE: 'Error updating user role',
  ERROR_DELETING_USER_ROLE: 'Error deleting user role',
  USER_CREATED_SUCCESSFULLY: 'User created successfully',
  USER_UPDATED_SUCCESSFULLY: 'User updated successfully',
  USER_ROLE_CREATED_SUCCESSFULLY: 'User role created successfully',
  USER_ROLE_UPDATES_SUCCESSFULLY: 'User role updated successfully',
  PROFILE_UPDATED_SUCCESSFULLY: 'Profile updated successfully',
  ERROR_UPDATING_PROFILE: 'Error updating profile',
} as const;
